import {test} from "@playwright/test"

// Dialogs are pop up boxes generated by Javascript, they are not part of the DOM

test("Handle Dialogs", async({page}) => {

    // d = dialog object
    page.on("dialog", async(d) => {         // This means, whenever any dialog appears -> run this handler

        // await d.accept("gvschbsjn")


        // returns a promise only
        if (d.type() == "alert") {
            await d.accept()
            // await d.defaultValue()          // Alerts don't have default value
        }
        

        else if (d.type() == "confirm") {
            await d.dismiss()
            // await d.message()        // returns text (not printed)
            console.log(await d.message());
        }


        else if (d.type() == "prompt") {
            await d.accept("hello")

            if (await d.defaultValue() == "harry potter") {
                console.log(await d.defaultValue());
                await d.accept()
            } else {
                await d.accept("tom")
            }
        }

    })

    await page.goto("https://testautomationpractice.blogspot.com/")

    await page.locator("//button[@id='alert-Btn']").click()

    await page.getByRole("button", {name : "Confirmation Alert"}).click()

    await page.getByRole("button", {name : "Prompt Alert"}).click()

})



// Dialogs are not HTML elements or locators, they are browser events..
// Golden Rule = "You don't FIND dialogs - you LISTEN for them"


// page.on("dialog", () => {})
// page.once("event", () => {})     -->     Only First Dialog



/**

 * 🧠 Difference:
- Method	        Behavior
-- on	            persistent listener
-- once	            one-time listener

 */




/**
 
Available methods on d : 

Method	                    Meaning
d.accept()	                Click OK
d.dismiss()	                Click Cancel
d.message()	                Get dialog text                 // also returns text
d.type()	                alert / confirm / prompt
d.defaultValue()	        default input (prompt only)

 */